language: scala

scala:
  - "2.13.1"
  - "2.12.10"
  - "2.11.12"

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk13

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: orVRfGwlahE6gApQJSCt1SSFIYJCN/JNGH0rBt44Ytbb9NdQlX0uVxlqhdemGuDL0/Kv4XjPxENEd04h6M9oqHCtFmGaNVKUnJd+pSbSnreYsykA2mayrN1sFyHNW6C3A+qAyDG/s4s+fiqHUkLtYMyDqkswqbi/6oEOxn5ISFx4MzXxug1SPVmxS+Nj/yTtk8ej9j3hOseDX56K0b/7o3/Xpzym6wGvBJ/vyGG71METCUClyPifjsVuBpzuJwplC3rPMCozJWBkIxxkRMiAP4q4WRsFkvJaDV3gHDhUuBkYfJXXBeZVbFkEbiP4JhV4TC6prKIw2Q0fBrOUtHPIN2LcVZyCN9N8zLhCLFpKlRw2ZpJ2+pxA5xti7DWzZblqd2q9z91s5c03K2IQ67ti1h5Y1KZyRLtMk3dlrNktevOqpvj7FABKctH04Be8jEb2V50X026JzrbbXO4DOYii7y5gzB3Mx/t6Xp1DgIYV7P924mpiVdlB3biS6htikmwuFpo3N9RCB3C15mPcOeqDh1eeComCqw+6E0gixdyDdIfdX+VyP5etncdih2spHmfbY2W7PNnAWuDoSB5yHEnM4RDHp0wN1OBoecc+8A2jhzmZqvpUxbj4FyEdyCjiKZiqINyYZg/M1FhfWYdRNn8tsRxssfsPjL9XUHj4mpPBk+Y=
  - secure: LaSQ5mvuTsMXPLvNiSZzBEFkvY8L3jEBxZGsNsGJHfxSpht2/euL0RhS2RzV1XCyWIcsLrFwc0G4YAJ6o1r1A1sPvIa4JVKSUiTjS6DALJZ3BV6kdpGlgVvrRXrXt6VUfHBiNkQXsK103FwFeOU3qpQ4n2X+dH73vdv9LWdBQOCvODv9LdNgHxQTwclU1Yw/PYBu8xCmb+tjQzLdQ6rpF3wSTB+3kxylto7rchQLa/sPX2lAQj01bNXV8fkQg/DDG+A2MsZY/47Nelf83h0ua9eagJayxmEtEh/oWKZcdFgG9JKATWnZ3Szhu+iP4LFLrnofR3H6PYx46e1NU1knUaQZ7YhsKcTgiIhROOIN6Fd5rXZh52zDOh03tdtf8S8JcsKcU7NdpGPJo6lu7EaKkN7GncTudyljcrqsx8zq4X0hAcPQtKDg/B4fYuqqpVQkcCT/xEtY8Zif04Cg29sXMmEUrYPldbE6xFIBWV339dVn6FBM8HcdrLMp/6ItVLYlZ3phoDTaizsjDcrURtuAhNk1zVoWK5hvVGBhxXtAS8OTi1K0blDhQqModREA3xV7PoRRPnUN1aQA2xq6utm+0rteV5wbBMorGplV9VT8tWef0Xi63ui7pU49d2ykOwAQw+YZhff0dMdV2ah/p4iW9MZUtJ3QdzCkDg32dp7SW6o=
  - secure: VGaNbl+3Ik2CW3J24YLxUKSsH+iQII6i26KvX8immNnoLR6XgG7AXIf+YJ9bpVwWdaXxsrTMr5hh2kxhNFUQCqwMI0TYFcK4cE88hUnS/dYbWqhFZLshXMA/+fLc3pQMDS3sUeOkl9/MT7AvkyX4okLfaxNQXxT5JGBz9E3nLP8zyZ0S9Bca+zYEFN2O9LiyRQ7CxKFIEMIIsisKMia6hwPPIpQaaqo7Vu8m+ipJWQekExdZMxJDFOKA0oH/Qitvkp90p+JVcZaY91p/LR5A8WFPrtFpRQSgyZJv+9cACzvHoCDGkPrp0ewmFdMeUdPABcZfeICpWz4WtoX/UdaFEIYT2a2Rlm3SJGt1Y7KPDruaBrODpqRyBEG5Aue01Dp72MhVBo4Hh4K9BqfGqsYYoeK3u5AGAl9J+kfONrGU1JBJvA9iZksjuiOPuKATmPCV90QEtZ962Ch8rIVNnJMfMyiDWMLOG6fW3Dfgqyk45sdSl95mfhUb2/R1jKDpM4GntgT0xYlQTsJ1+v5CqvNZpUpSVeqGtt+qSYDJi0c2ez/QkGn8zC2r/aUnbjMJ+hksnm4KTTJSW52bvbKlVAWUnMVct+hMvliEFBO1WXyRghkMVw7AKg7Nr7XvMC4dDcnhj6N6JCP/BoirOkmSgaT77/8G6rBs4GIWqT3u7ZgiFsQ=
  - secure: jfd4kY2nDdQ1BxoK9b9xzFEsUPQZpzeqW75OUfc7jwjcSuIqIcoNLcso30Nff75JMnEWOluZYYllMEAHO2xtwGLfyxXgw7sH5ra81AdVG3LwrOWLVD4iuo1pryw/itBk0Eb8S9OBx48V10PEA2z8gaYAi1IVh/XsDbPw2asK91hnXRPUX5Z4hX7p2TC97h4Wq/RqxhJ281Q/OVKv4X7rEi5Soplry6og6Vfr0wWBaVw6/slcSgZLIQRb2lkdRSJGKKKyvOEf8+iwKIZT7sYnfIULs4OHFgNPkjMQamcJxbLDdF+lPprbG1SEHpJ1sPkhd5uctOc7ZBSYl+3f0VRMFHl0ldrnca83XI/zE10bvjj1SXCttwuIBwxnypCsvGYKzQ+2catFwrQIKeF8rmJLkfQ3t18A1ak8EwU0QDNW5FHFyEVKyxZwAxULsNJ2UkK8WfuNCjm9h29h+bbmUNL3WrbnRaJ8S6X07sKOaLKkRK7PCCJiAcdqRXrUcVZBBTdMXaJT6rgSMLD6BndEFyYn0E4xqnruIwbVB7Hu//lXKtdls5jUpHlzRWB4n72pETdPvBPPxiC8bkxzBxzWReec3n6b1gXsVxTFQHlxB/IGEwsJFD1vr3Xi0Ct5f8K7NwmFKIYDWH0zP+/48+CFctCzKMizfmlp8QpwcBrAao9yeEw=
